# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-04 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_block1', mezzanine.core.fields.RichTextField(verbose_name='Content for block1')),
                ('text_block1_fr', mezzanine.core.fields.RichTextField(null=True, verbose_name='Content for block1')),
                ('text_block1_en', mezzanine.core.fields.RichTextField(null=True, verbose_name='Content for block1')),
                ('photo1', models.ImageField(upload_to='upload/', verbose_name='Photo for block1')),
                ('text_block2', mezzanine.core.fields.RichTextField(verbose_name='Content for block2')),
                ('text_block2_fr', mezzanine.core.fields.RichTextField(null=True, verbose_name='Content for block2')),
                ('text_block2_en', mezzanine.core.fields.RichTextField(null=True, verbose_name='Content for block2')),
                ('photo2', models.ImageField(upload_to='upload/', verbose_name='Photo for block2')),
                ('text_block3', mezzanine.core.fields.RichTextField(verbose_name='Content for block3')),
                ('text_block3_fr', mezzanine.core.fields.RichTextField(null=True, verbose_name='Content for block3')),
                ('text_block3_en', mezzanine.core.fields.RichTextField(null=True, verbose_name='Content for block3')),
                ('photo3', models.ImageField(upload_to='upload/', verbose_name='Photo for block3')),
                ('text_block4', mezzanine.core.fields.RichTextField(verbose_name='Content for block4')),
                ('text_block4_fr', mezzanine.core.fields.RichTextField(null=True, verbose_name='Content for block4')),
                ('text_block4_en', mezzanine.core.fields.RichTextField(null=True, verbose_name='Content for block4')),
                ('photo4', models.ImageField(upload_to='upload/', verbose_name='Photo for block4')),
                ('extra_css_for_page', models.CharField(help_text='for exemple: .green-room {background-color: #9D090E;color: white;}', max_length=2000, verbose_name='CSS to add to page')),
            ],
        ),
    ]
