# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-04 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='extra_css_for_page',
            field=models.CharField(blank=True, help_text='for exemple: .green-room {background-color: #9D090E;color: white;}', max_length=2000, null=True, verbose_name='CSS to add to page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='Photo for block1'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='Photo for block2'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='Photo for block3'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='Photo for block4'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text_block1',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Content for block1'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text_block1_en',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Content for block1'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text_block1_fr',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Content for block1'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text_block2',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Content for block2'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text_block2_en',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Content for block2'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text_block2_fr',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Content for block2'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text_block3',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Content for block3'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text_block3_en',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Content for block3'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text_block3_fr',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Content for block3'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text_block4',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Content for block4'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text_block4_en',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Content for block4'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text_block4_fr',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Content for block4'),
        ),
    ]
