# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-04 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_startpage_startpagesection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='startpagesection',
            name='container_startpage',
        ),
        migrations.DeleteModel(
            name='StartPage',
        ),
        migrations.DeleteModel(
            name='StartPageSection',
        ),
    ]
