# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-04 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_homepagesection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='text_block1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='text_block1_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='text_block1_fr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='text_block2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='text_block2_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='text_block2_fr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='text_block3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='text_block3_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='text_block3_fr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='text_block4',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='text_block4_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='text_block4_fr',
        ),
    ]
