# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190517_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='season_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Season'),
        ),
        migrations.AddField(
            model_name='product',
            name='season_fr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Season'),
        ),
        migrations.AddField(
            model_name='productspage',
            name='content_en',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='productspage',
            name='content_fr',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
    ]
